/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FirewallInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addGlobalPolicy"
      | "addGlobalPolicyForConsumers"
      | "addPolicies"
      | "addPolicy"
      | "approvedPolicies"
      | "dryrunEnabled"
      | "postExecution"
      | "preExecution"
      | "removeGlobalPolicy"
      | "removeGlobalPolicyForConsumers"
      | "removePolicies"
      | "removePolicy"
      | "setConsumerDryrunStatus"
      | "setPolicyStatus"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConsumerDryrunStatusUpdate"
      | "DryrunPolicyPostError"
      | "DryrunPolicyPostSuccess"
      | "DryrunPolicyPreError"
      | "DryrunPolicyPreSuccess"
      | "GlobalDryrunPolicyPostError"
      | "GlobalDryrunPolicyPostSuccess"
      | "GlobalDryrunPolicyPreError"
      | "GlobalDryrunPolicyPreSuccess"
      | "GlobalPolicyAdded"
      | "GlobalPolicyPostSuccess"
      | "GlobalPolicyPreSuccess"
      | "GlobalPolicyRemoved"
      | "PolicyAdded"
      | "PolicyPostSuccess"
      | "PolicyPreSuccess"
      | "PolicyRemoved"
      | "PolicyStatusUpdate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addGlobalPolicy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addGlobalPolicyForConsumers",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPolicies",
    values: [AddressLike, BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addPolicy",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedPolicies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dryrunEnabled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postExecution",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "preExecution",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGlobalPolicy",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGlobalPolicyForConsumers",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePolicies",
    values: [AddressLike, BytesLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removePolicy",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setConsumerDryrunStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addGlobalPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addGlobalPolicyForConsumers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvedPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dryrunEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGlobalPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGlobalPolicyForConsumers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConsumerDryrunStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ConsumerDryrunStatusUpdateEvent {
  export type InputTuple = [consumer: AddressLike, status: boolean];
  export type OutputTuple = [consumer: string, status: boolean];
  export interface OutputObject {
    consumer: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DryrunPolicyPostErrorEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike,
    error: BytesLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string,
    error: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
    error: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DryrunPolicyPostSuccessEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DryrunPolicyPreErrorEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike,
    error: BytesLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string,
    error: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
    error: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DryrunPolicyPreSuccessEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalDryrunPolicyPostErrorEvent {
  export type InputTuple = [
    consumer: AddressLike,
    policy: AddressLike,
    error: BytesLike
  ];
  export type OutputTuple = [consumer: string, policy: string, error: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
    error: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalDryrunPolicyPostSuccessEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalDryrunPolicyPreErrorEvent {
  export type InputTuple = [
    consumer: AddressLike,
    policy: AddressLike,
    error: BytesLike
  ];
  export type OutputTuple = [consumer: string, policy: string, error: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
    error: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalDryrunPolicyPreSuccessEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPolicyAddedEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPolicyPostSuccessEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPolicyPreSuccessEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalPolicyRemovedEvent {
  export type InputTuple = [consumer: AddressLike, policy: AddressLike];
  export type OutputTuple = [consumer: string, policy: string];
  export interface OutputObject {
    consumer: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyAddedEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPostSuccessEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPreSuccessEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRemovedEvent {
  export type InputTuple = [
    consumer: AddressLike,
    methodSig: BytesLike,
    policy: AddressLike
  ];
  export type OutputTuple = [
    consumer: string,
    methodSig: string,
    policy: string
  ];
  export interface OutputObject {
    consumer: string;
    methodSig: string;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyStatusUpdateEvent {
  export type InputTuple = [policy: AddressLike, status: boolean];
  export type OutputTuple = [policy: string, status: boolean];
  export interface OutputObject {
    policy: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Firewall extends BaseContract {
  connect(runner?: ContractRunner | null): Firewall;
  waitForDeployment(): Promise<this>;

  interface: FirewallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addGlobalPolicy: TypedContractMethod<
    [_consumer: AddressLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  addGlobalPolicyForConsumers: TypedContractMethod<
    [_consumers: AddressLike[], _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  addPolicies: TypedContractMethod<
    [
      _consumer: AddressLike,
      _methodSigs: BytesLike[],
      _policies: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  addPolicy: TypedContractMethod<
    [_consumer: AddressLike, _methodSig: BytesLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  approvedPolicies: TypedContractMethod<
    [_policy: AddressLike],
    [boolean],
    "view"
  >;

  dryrunEnabled: TypedContractMethod<
    [_consumer: AddressLike],
    [boolean],
    "view"
  >;

  postExecution: TypedContractMethod<
    [_sender: AddressLike, _data: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  preExecution: TypedContractMethod<
    [_sender: AddressLike, _data: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeGlobalPolicy: TypedContractMethod<
    [_consumer: AddressLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  removeGlobalPolicyForConsumers: TypedContractMethod<
    [_consumers: AddressLike[], _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  removePolicies: TypedContractMethod<
    [
      _consumer: AddressLike,
      _methodSigs: BytesLike[],
      _policies: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  removePolicy: TypedContractMethod<
    [_consumer: AddressLike, _methodSig: BytesLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;

  setConsumerDryrunStatus: TypedContractMethod<
    [_consumer: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setPolicyStatus: TypedContractMethod<
    [_policy: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addGlobalPolicy"
  ): TypedContractMethod<
    [_consumer: AddressLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addGlobalPolicyForConsumers"
  ): TypedContractMethod<
    [_consumers: AddressLike[], _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPolicies"
  ): TypedContractMethod<
    [
      _consumer: AddressLike,
      _methodSigs: BytesLike[],
      _policies: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPolicy"
  ): TypedContractMethod<
    [_consumer: AddressLike, _methodSig: BytesLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedPolicies"
  ): TypedContractMethod<[_policy: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dryrunEnabled"
  ): TypedContractMethod<[_consumer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "postExecution"
  ): TypedContractMethod<
    [_sender: AddressLike, _data: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "preExecution"
  ): TypedContractMethod<
    [_sender: AddressLike, _data: BytesLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeGlobalPolicy"
  ): TypedContractMethod<
    [_consumer: AddressLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeGlobalPolicyForConsumers"
  ): TypedContractMethod<
    [_consumers: AddressLike[], _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removePolicies"
  ): TypedContractMethod<
    [
      _consumer: AddressLike,
      _methodSigs: BytesLike[],
      _policies: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removePolicy"
  ): TypedContractMethod<
    [_consumer: AddressLike, _methodSig: BytesLike, _policy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConsumerDryrunStatus"
  ): TypedContractMethod<
    [_consumer: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPolicyStatus"
  ): TypedContractMethod<
    [_policy: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ConsumerDryrunStatusUpdate"
  ): TypedContractEvent<
    ConsumerDryrunStatusUpdateEvent.InputTuple,
    ConsumerDryrunStatusUpdateEvent.OutputTuple,
    ConsumerDryrunStatusUpdateEvent.OutputObject
  >;
  getEvent(
    key: "DryrunPolicyPostError"
  ): TypedContractEvent<
    DryrunPolicyPostErrorEvent.InputTuple,
    DryrunPolicyPostErrorEvent.OutputTuple,
    DryrunPolicyPostErrorEvent.OutputObject
  >;
  getEvent(
    key: "DryrunPolicyPostSuccess"
  ): TypedContractEvent<
    DryrunPolicyPostSuccessEvent.InputTuple,
    DryrunPolicyPostSuccessEvent.OutputTuple,
    DryrunPolicyPostSuccessEvent.OutputObject
  >;
  getEvent(
    key: "DryrunPolicyPreError"
  ): TypedContractEvent<
    DryrunPolicyPreErrorEvent.InputTuple,
    DryrunPolicyPreErrorEvent.OutputTuple,
    DryrunPolicyPreErrorEvent.OutputObject
  >;
  getEvent(
    key: "DryrunPolicyPreSuccess"
  ): TypedContractEvent<
    DryrunPolicyPreSuccessEvent.InputTuple,
    DryrunPolicyPreSuccessEvent.OutputTuple,
    DryrunPolicyPreSuccessEvent.OutputObject
  >;
  getEvent(
    key: "GlobalDryrunPolicyPostError"
  ): TypedContractEvent<
    GlobalDryrunPolicyPostErrorEvent.InputTuple,
    GlobalDryrunPolicyPostErrorEvent.OutputTuple,
    GlobalDryrunPolicyPostErrorEvent.OutputObject
  >;
  getEvent(
    key: "GlobalDryrunPolicyPostSuccess"
  ): TypedContractEvent<
    GlobalDryrunPolicyPostSuccessEvent.InputTuple,
    GlobalDryrunPolicyPostSuccessEvent.OutputTuple,
    GlobalDryrunPolicyPostSuccessEvent.OutputObject
  >;
  getEvent(
    key: "GlobalDryrunPolicyPreError"
  ): TypedContractEvent<
    GlobalDryrunPolicyPreErrorEvent.InputTuple,
    GlobalDryrunPolicyPreErrorEvent.OutputTuple,
    GlobalDryrunPolicyPreErrorEvent.OutputObject
  >;
  getEvent(
    key: "GlobalDryrunPolicyPreSuccess"
  ): TypedContractEvent<
    GlobalDryrunPolicyPreSuccessEvent.InputTuple,
    GlobalDryrunPolicyPreSuccessEvent.OutputTuple,
    GlobalDryrunPolicyPreSuccessEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPolicyAdded"
  ): TypedContractEvent<
    GlobalPolicyAddedEvent.InputTuple,
    GlobalPolicyAddedEvent.OutputTuple,
    GlobalPolicyAddedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPolicyPostSuccess"
  ): TypedContractEvent<
    GlobalPolicyPostSuccessEvent.InputTuple,
    GlobalPolicyPostSuccessEvent.OutputTuple,
    GlobalPolicyPostSuccessEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPolicyPreSuccess"
  ): TypedContractEvent<
    GlobalPolicyPreSuccessEvent.InputTuple,
    GlobalPolicyPreSuccessEvent.OutputTuple,
    GlobalPolicyPreSuccessEvent.OutputObject
  >;
  getEvent(
    key: "GlobalPolicyRemoved"
  ): TypedContractEvent<
    GlobalPolicyRemovedEvent.InputTuple,
    GlobalPolicyRemovedEvent.OutputTuple,
    GlobalPolicyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyAdded"
  ): TypedContractEvent<
    PolicyAddedEvent.InputTuple,
    PolicyAddedEvent.OutputTuple,
    PolicyAddedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPostSuccess"
  ): TypedContractEvent<
    PolicyPostSuccessEvent.InputTuple,
    PolicyPostSuccessEvent.OutputTuple,
    PolicyPostSuccessEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPreSuccess"
  ): TypedContractEvent<
    PolicyPreSuccessEvent.InputTuple,
    PolicyPreSuccessEvent.OutputTuple,
    PolicyPreSuccessEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRemoved"
  ): TypedContractEvent<
    PolicyRemovedEvent.InputTuple,
    PolicyRemovedEvent.OutputTuple,
    PolicyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyStatusUpdate"
  ): TypedContractEvent<
    PolicyStatusUpdateEvent.InputTuple,
    PolicyStatusUpdateEvent.OutputTuple,
    PolicyStatusUpdateEvent.OutputObject
  >;

  filters: {
    "ConsumerDryrunStatusUpdate(address,bool)": TypedContractEvent<
      ConsumerDryrunStatusUpdateEvent.InputTuple,
      ConsumerDryrunStatusUpdateEvent.OutputTuple,
      ConsumerDryrunStatusUpdateEvent.OutputObject
    >;
    ConsumerDryrunStatusUpdate: TypedContractEvent<
      ConsumerDryrunStatusUpdateEvent.InputTuple,
      ConsumerDryrunStatusUpdateEvent.OutputTuple,
      ConsumerDryrunStatusUpdateEvent.OutputObject
    >;

    "DryrunPolicyPostError(address,bytes4,address,bytes)": TypedContractEvent<
      DryrunPolicyPostErrorEvent.InputTuple,
      DryrunPolicyPostErrorEvent.OutputTuple,
      DryrunPolicyPostErrorEvent.OutputObject
    >;
    DryrunPolicyPostError: TypedContractEvent<
      DryrunPolicyPostErrorEvent.InputTuple,
      DryrunPolicyPostErrorEvent.OutputTuple,
      DryrunPolicyPostErrorEvent.OutputObject
    >;

    "DryrunPolicyPostSuccess(address,bytes4,address)": TypedContractEvent<
      DryrunPolicyPostSuccessEvent.InputTuple,
      DryrunPolicyPostSuccessEvent.OutputTuple,
      DryrunPolicyPostSuccessEvent.OutputObject
    >;
    DryrunPolicyPostSuccess: TypedContractEvent<
      DryrunPolicyPostSuccessEvent.InputTuple,
      DryrunPolicyPostSuccessEvent.OutputTuple,
      DryrunPolicyPostSuccessEvent.OutputObject
    >;

    "DryrunPolicyPreError(address,bytes4,address,bytes)": TypedContractEvent<
      DryrunPolicyPreErrorEvent.InputTuple,
      DryrunPolicyPreErrorEvent.OutputTuple,
      DryrunPolicyPreErrorEvent.OutputObject
    >;
    DryrunPolicyPreError: TypedContractEvent<
      DryrunPolicyPreErrorEvent.InputTuple,
      DryrunPolicyPreErrorEvent.OutputTuple,
      DryrunPolicyPreErrorEvent.OutputObject
    >;

    "DryrunPolicyPreSuccess(address,bytes4,address)": TypedContractEvent<
      DryrunPolicyPreSuccessEvent.InputTuple,
      DryrunPolicyPreSuccessEvent.OutputTuple,
      DryrunPolicyPreSuccessEvent.OutputObject
    >;
    DryrunPolicyPreSuccess: TypedContractEvent<
      DryrunPolicyPreSuccessEvent.InputTuple,
      DryrunPolicyPreSuccessEvent.OutputTuple,
      DryrunPolicyPreSuccessEvent.OutputObject
    >;

    "GlobalDryrunPolicyPostError(address,address,bytes)": TypedContractEvent<
      GlobalDryrunPolicyPostErrorEvent.InputTuple,
      GlobalDryrunPolicyPostErrorEvent.OutputTuple,
      GlobalDryrunPolicyPostErrorEvent.OutputObject
    >;
    GlobalDryrunPolicyPostError: TypedContractEvent<
      GlobalDryrunPolicyPostErrorEvent.InputTuple,
      GlobalDryrunPolicyPostErrorEvent.OutputTuple,
      GlobalDryrunPolicyPostErrorEvent.OutputObject
    >;

    "GlobalDryrunPolicyPostSuccess(address,address)": TypedContractEvent<
      GlobalDryrunPolicyPostSuccessEvent.InputTuple,
      GlobalDryrunPolicyPostSuccessEvent.OutputTuple,
      GlobalDryrunPolicyPostSuccessEvent.OutputObject
    >;
    GlobalDryrunPolicyPostSuccess: TypedContractEvent<
      GlobalDryrunPolicyPostSuccessEvent.InputTuple,
      GlobalDryrunPolicyPostSuccessEvent.OutputTuple,
      GlobalDryrunPolicyPostSuccessEvent.OutputObject
    >;

    "GlobalDryrunPolicyPreError(address,address,bytes)": TypedContractEvent<
      GlobalDryrunPolicyPreErrorEvent.InputTuple,
      GlobalDryrunPolicyPreErrorEvent.OutputTuple,
      GlobalDryrunPolicyPreErrorEvent.OutputObject
    >;
    GlobalDryrunPolicyPreError: TypedContractEvent<
      GlobalDryrunPolicyPreErrorEvent.InputTuple,
      GlobalDryrunPolicyPreErrorEvent.OutputTuple,
      GlobalDryrunPolicyPreErrorEvent.OutputObject
    >;

    "GlobalDryrunPolicyPreSuccess(address,address)": TypedContractEvent<
      GlobalDryrunPolicyPreSuccessEvent.InputTuple,
      GlobalDryrunPolicyPreSuccessEvent.OutputTuple,
      GlobalDryrunPolicyPreSuccessEvent.OutputObject
    >;
    GlobalDryrunPolicyPreSuccess: TypedContractEvent<
      GlobalDryrunPolicyPreSuccessEvent.InputTuple,
      GlobalDryrunPolicyPreSuccessEvent.OutputTuple,
      GlobalDryrunPolicyPreSuccessEvent.OutputObject
    >;

    "GlobalPolicyAdded(address,address)": TypedContractEvent<
      GlobalPolicyAddedEvent.InputTuple,
      GlobalPolicyAddedEvent.OutputTuple,
      GlobalPolicyAddedEvent.OutputObject
    >;
    GlobalPolicyAdded: TypedContractEvent<
      GlobalPolicyAddedEvent.InputTuple,
      GlobalPolicyAddedEvent.OutputTuple,
      GlobalPolicyAddedEvent.OutputObject
    >;

    "GlobalPolicyPostSuccess(address,address)": TypedContractEvent<
      GlobalPolicyPostSuccessEvent.InputTuple,
      GlobalPolicyPostSuccessEvent.OutputTuple,
      GlobalPolicyPostSuccessEvent.OutputObject
    >;
    GlobalPolicyPostSuccess: TypedContractEvent<
      GlobalPolicyPostSuccessEvent.InputTuple,
      GlobalPolicyPostSuccessEvent.OutputTuple,
      GlobalPolicyPostSuccessEvent.OutputObject
    >;

    "GlobalPolicyPreSuccess(address,address)": TypedContractEvent<
      GlobalPolicyPreSuccessEvent.InputTuple,
      GlobalPolicyPreSuccessEvent.OutputTuple,
      GlobalPolicyPreSuccessEvent.OutputObject
    >;
    GlobalPolicyPreSuccess: TypedContractEvent<
      GlobalPolicyPreSuccessEvent.InputTuple,
      GlobalPolicyPreSuccessEvent.OutputTuple,
      GlobalPolicyPreSuccessEvent.OutputObject
    >;

    "GlobalPolicyRemoved(address,address)": TypedContractEvent<
      GlobalPolicyRemovedEvent.InputTuple,
      GlobalPolicyRemovedEvent.OutputTuple,
      GlobalPolicyRemovedEvent.OutputObject
    >;
    GlobalPolicyRemoved: TypedContractEvent<
      GlobalPolicyRemovedEvent.InputTuple,
      GlobalPolicyRemovedEvent.OutputTuple,
      GlobalPolicyRemovedEvent.OutputObject
    >;

    "PolicyAdded(address,bytes4,address)": TypedContractEvent<
      PolicyAddedEvent.InputTuple,
      PolicyAddedEvent.OutputTuple,
      PolicyAddedEvent.OutputObject
    >;
    PolicyAdded: TypedContractEvent<
      PolicyAddedEvent.InputTuple,
      PolicyAddedEvent.OutputTuple,
      PolicyAddedEvent.OutputObject
    >;

    "PolicyPostSuccess(address,bytes4,address)": TypedContractEvent<
      PolicyPostSuccessEvent.InputTuple,
      PolicyPostSuccessEvent.OutputTuple,
      PolicyPostSuccessEvent.OutputObject
    >;
    PolicyPostSuccess: TypedContractEvent<
      PolicyPostSuccessEvent.InputTuple,
      PolicyPostSuccessEvent.OutputTuple,
      PolicyPostSuccessEvent.OutputObject
    >;

    "PolicyPreSuccess(address,bytes4,address)": TypedContractEvent<
      PolicyPreSuccessEvent.InputTuple,
      PolicyPreSuccessEvent.OutputTuple,
      PolicyPreSuccessEvent.OutputObject
    >;
    PolicyPreSuccess: TypedContractEvent<
      PolicyPreSuccessEvent.InputTuple,
      PolicyPreSuccessEvent.OutputTuple,
      PolicyPreSuccessEvent.OutputObject
    >;

    "PolicyRemoved(address,bytes4,address)": TypedContractEvent<
      PolicyRemovedEvent.InputTuple,
      PolicyRemovedEvent.OutputTuple,
      PolicyRemovedEvent.OutputObject
    >;
    PolicyRemoved: TypedContractEvent<
      PolicyRemovedEvent.InputTuple,
      PolicyRemovedEvent.OutputTuple,
      PolicyRemovedEvent.OutputObject
    >;

    "PolicyStatusUpdate(address,bool)": TypedContractEvent<
      PolicyStatusUpdateEvent.InputTuple,
      PolicyStatusUpdateEvent.OutputTuple,
      PolicyStatusUpdateEvent.OutputObject
    >;
    PolicyStatusUpdate: TypedContractEvent<
      PolicyStatusUpdateEvent.InputTuple,
      PolicyStatusUpdateEvent.OutputTuple,
      PolicyStatusUpdateEvent.OutputObject
    >;
  };
}
