/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IProtocolRegistry {
  export type ProtocolStruct = {
    policyAddress: AddressLike;
    metadataURI: string;
  };

  export type ProtocolStructOutput = [
    policyAddress: string,
    metadataURI: string
  ] & { policyAddress: string; metadataURI: string };

  export type ProtocolDetectionStruct = {
    protocolAdmin: AddressLike;
    operator: AddressLike;
    assets: AddressLike[];
    admins: AddressLike[];
    vennFee: BigNumberish;
    isApproved: boolean;
    metadataURI: string;
  };

  export type ProtocolDetectionStructOutput = [
    protocolAdmin: string,
    operator: string,
    assets: string[],
    admins: string[],
    vennFee: bigint,
    isApproved: boolean,
    metadataURI: string
  ] & {
    protocolAdmin: string;
    operator: string;
    assets: string[];
    admins: string[];
    vennFee: bigint;
    isApproved: boolean;
    metadataURI: string;
  };
}

export interface ProtocolRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_VENN_DETECTION_FEE"
      | "MAX_VENN_PROTOCOL_FEE"
      | "__ProtocolRegistry_init"
      | "approveProtocolDetectionAsOperator"
      | "attestationCenter"
      | "createAndRegisterProtocolDetection"
      | "getProtocol"
      | "getProtocolDetection"
      | "getProtocolTaskDefinitionIds"
      | "getRequiredOperatorIds"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isSubnetSubscribed"
      | "proxiableUUID"
      | "registerProtocol"
      | "renounceRole"
      | "revokeRole"
      | "setAttestationCenter"
      | "setVennDetectionFee"
      | "setVennFeeRecipient"
      | "setVennProtocolFee"
      | "subscribeSubnet"
      | "supportsInterface"
      | "unsubscribeSubnet"
      | "updateProtocol"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "vennDetectionFee"
      | "vennFeeRecipient"
      | "vennProtocolFee"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminChanged"
      | "AttestationCenterSet"
      | "BeaconUpgraded"
      | "Initialized"
      | "ProtocolDetectionApproved"
      | "ProtocolDetectionRegistered"
      | "ProtocolRegistered"
      | "ProtocolUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubnetSubscribed"
      | "SubnetUnsubscribed"
      | "Upgraded"
      | "VennDetectionFeeSet"
      | "VennFeeRecipientSet"
      | "VennProtocolFeeSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VENN_DETECTION_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VENN_PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "__ProtocolRegistry_init",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveProtocolDetectionAsOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationCenter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAndRegisterProtocolDetection",
    values: [AddressLike, AddressLike[], AddressLike[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocol",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolDetection",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocolTaskDefinitionIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredOperatorIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubnetSubscribed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerProtocol",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestationCenter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVennDetectionFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVennFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVennProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeSubnet",
    values: [AddressLike, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribeSubnet",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProtocol",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vennDetectionFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vennFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vennProtocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VENN_DETECTION_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VENN_PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__ProtocolRegistry_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveProtocolDetectionAsOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestationCenter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAndRegisterProtocolDetection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolDetection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocolTaskDefinitionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredOperatorIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSubnetSubscribed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttestationCenter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVennDetectionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVennFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVennProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscribeSubnet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribeSubnet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vennDetectionFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vennFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vennProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationCenterSetEvent {
  export type InputTuple = [attestationCenter: AddressLike];
  export type OutputTuple = [attestationCenter: string];
  export interface OutputObject {
    attestationCenter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolDetectionApprovedEvent {
  export type InputTuple = [
    detectionEscrow: AddressLike,
    operator: AddressLike,
    assets: AddressLike[],
    admins: AddressLike[],
    metadataURI: string
  ];
  export type OutputTuple = [
    detectionEscrow: string,
    operator: string,
    assets: string[],
    admins: string[],
    metadataURI: string
  ];
  export interface OutputObject {
    detectionEscrow: string;
    operator: string;
    assets: string[];
    admins: string[];
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolDetectionRegisteredEvent {
  export type InputTuple = [
    detectionEscrow: AddressLike,
    operator: AddressLike,
    assets: AddressLike[],
    admins: AddressLike[],
    fee: BigNumberish,
    metadataURI: string
  ];
  export type OutputTuple = [
    detectionEscrow: string,
    operator: string,
    assets: string[],
    admins: string[],
    fee: bigint,
    metadataURI: string
  ];
  export interface OutputObject {
    detectionEscrow: string;
    operator: string;
    assets: string[];
    admins: string[];
    fee: bigint;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolRegisteredEvent {
  export type InputTuple = [policyAddress: AddressLike, metadataURI: string];
  export type OutputTuple = [policyAddress: string, metadataURI: string];
  export interface OutputObject {
    policyAddress: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolUpdatedEvent {
  export type InputTuple = [policyAddress: AddressLike, metadataURI: string];
  export type OutputTuple = [policyAddress: string, metadataURI: string];
  export interface OutputObject {
    policyAddress: string;
    metadataURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnetSubscribedEvent {
  export type InputTuple = [
    policyAddress: AddressLike,
    taskDefinitionId: BigNumberish,
    requiredOperatorIds: BigNumberish[]
  ];
  export type OutputTuple = [
    policyAddress: string,
    taskDefinitionId: bigint,
    requiredOperatorIds: bigint[]
  ];
  export interface OutputObject {
    policyAddress: string;
    taskDefinitionId: bigint;
    requiredOperatorIds: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubnetUnsubscribedEvent {
  export type InputTuple = [
    policyAddress: AddressLike,
    taskDefinitionId: BigNumberish
  ];
  export type OutputTuple = [policyAddress: string, taskDefinitionId: bigint];
  export interface OutputObject {
    policyAddress: string;
    taskDefinitionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VennDetectionFeeSetEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VennFeeRecipientSetEvent {
  export type InputTuple = [vennFeeRecipient: AddressLike];
  export type OutputTuple = [vennFeeRecipient: string];
  export interface OutputObject {
    vennFeeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VennProtocolFeeSetEvent {
  export type InputTuple = [fee: BigNumberish];
  export type OutputTuple = [fee: bigint];
  export interface OutputObject {
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProtocolRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProtocolRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProtocolRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_VENN_DETECTION_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_VENN_PROTOCOL_FEE: TypedContractMethod<[], [bigint], "view">;

  __ProtocolRegistry_init: TypedContractMethod<
    [
      _attestationCenter: AddressLike,
      _vennFeeRecipient: AddressLike,
      _vennDetectionFee: BigNumberish,
      _vennProtocolFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  approveProtocolDetectionAsOperator: TypedContractMethod<
    [_detectionEscrow: AddressLike],
    [void],
    "nonpayable"
  >;

  attestationCenter: TypedContractMethod<[], [string], "view">;

  createAndRegisterProtocolDetection: TypedContractMethod<
    [
      _operator: AddressLike,
      _assets: AddressLike[],
      _admins: AddressLike[],
      _metadataURI: string
    ],
    [string],
    "nonpayable"
  >;

  getProtocol: TypedContractMethod<
    [_policyAddress: AddressLike],
    [IProtocolRegistry.ProtocolStructOutput],
    "view"
  >;

  getProtocolDetection: TypedContractMethod<
    [_detectionEscrow: AddressLike],
    [IProtocolRegistry.ProtocolDetectionStructOutput],
    "view"
  >;

  getProtocolTaskDefinitionIds: TypedContractMethod<
    [_policyAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getRequiredOperatorIds: TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isSubnetSubscribed: TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [boolean],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerProtocol: TypedContractMethod<
    [_policyAddress: AddressLike, _metadataURI: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAttestationCenter: TypedContractMethod<
    [_attestationCenter: AddressLike],
    [void],
    "nonpayable"
  >;

  setVennDetectionFee: TypedContractMethod<
    [_vennDetectionFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVennFeeRecipient: TypedContractMethod<
    [_vennFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setVennProtocolFee: TypedContractMethod<
    [_vennProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribeSubnet: TypedContractMethod<
    [
      _policyAddress: AddressLike,
      _taskDefinitionId: BigNumberish,
      _requiredOperatorIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unsubscribeSubnet: TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateProtocol: TypedContractMethod<
    [_policyAddress: AddressLike, _metadataURI: string],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  vennDetectionFee: TypedContractMethod<[], [bigint], "view">;

  vennFeeRecipient: TypedContractMethod<[], [string], "view">;

  vennProtocolFee: TypedContractMethod<[], [bigint], "view">;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_VENN_DETECTION_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VENN_PROTOCOL_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "__ProtocolRegistry_init"
  ): TypedContractMethod<
    [
      _attestationCenter: AddressLike,
      _vennFeeRecipient: AddressLike,
      _vennDetectionFee: BigNumberish,
      _vennProtocolFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveProtocolDetectionAsOperator"
  ): TypedContractMethod<[_detectionEscrow: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attestationCenter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAndRegisterProtocolDetection"
  ): TypedContractMethod<
    [
      _operator: AddressLike,
      _assets: AddressLike[],
      _admins: AddressLike[],
      _metadataURI: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProtocol"
  ): TypedContractMethod<
    [_policyAddress: AddressLike],
    [IProtocolRegistry.ProtocolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolDetection"
  ): TypedContractMethod<
    [_detectionEscrow: AddressLike],
    [IProtocolRegistry.ProtocolDetectionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocolTaskDefinitionIds"
  ): TypedContractMethod<[_policyAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRequiredOperatorIds"
  ): TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isSubnetSubscribed"
  ): TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerProtocol"
  ): TypedContractMethod<
    [_policyAddress: AddressLike, _metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttestationCenter"
  ): TypedContractMethod<
    [_attestationCenter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVennDetectionFee"
  ): TypedContractMethod<
    [_vennDetectionFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVennFeeRecipient"
  ): TypedContractMethod<
    [_vennFeeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVennProtocolFee"
  ): TypedContractMethod<
    [_vennProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribeSubnet"
  ): TypedContractMethod<
    [
      _policyAddress: AddressLike,
      _taskDefinitionId: BigNumberish,
      _requiredOperatorIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unsubscribeSubnet"
  ): TypedContractMethod<
    [_policyAddress: AddressLike, _taskDefinitionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProtocol"
  ): TypedContractMethod<
    [_policyAddress: AddressLike, _metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "vennDetectionFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vennFeeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vennProtocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationCenterSet"
  ): TypedContractEvent<
    AttestationCenterSetEvent.InputTuple,
    AttestationCenterSetEvent.OutputTuple,
    AttestationCenterSetEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolDetectionApproved"
  ): TypedContractEvent<
    ProtocolDetectionApprovedEvent.InputTuple,
    ProtocolDetectionApprovedEvent.OutputTuple,
    ProtocolDetectionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolDetectionRegistered"
  ): TypedContractEvent<
    ProtocolDetectionRegisteredEvent.InputTuple,
    ProtocolDetectionRegisteredEvent.OutputTuple,
    ProtocolDetectionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolRegistered"
  ): TypedContractEvent<
    ProtocolRegisteredEvent.InputTuple,
    ProtocolRegisteredEvent.OutputTuple,
    ProtocolRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolUpdated"
  ): TypedContractEvent<
    ProtocolUpdatedEvent.InputTuple,
    ProtocolUpdatedEvent.OutputTuple,
    ProtocolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubnetSubscribed"
  ): TypedContractEvent<
    SubnetSubscribedEvent.InputTuple,
    SubnetSubscribedEvent.OutputTuple,
    SubnetSubscribedEvent.OutputObject
  >;
  getEvent(
    key: "SubnetUnsubscribed"
  ): TypedContractEvent<
    SubnetUnsubscribedEvent.InputTuple,
    SubnetUnsubscribedEvent.OutputTuple,
    SubnetUnsubscribedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VennDetectionFeeSet"
  ): TypedContractEvent<
    VennDetectionFeeSetEvent.InputTuple,
    VennDetectionFeeSetEvent.OutputTuple,
    VennDetectionFeeSetEvent.OutputObject
  >;
  getEvent(
    key: "VennFeeRecipientSet"
  ): TypedContractEvent<
    VennFeeRecipientSetEvent.InputTuple,
    VennFeeRecipientSetEvent.OutputTuple,
    VennFeeRecipientSetEvent.OutputObject
  >;
  getEvent(
    key: "VennProtocolFeeSet"
  ): TypedContractEvent<
    VennProtocolFeeSetEvent.InputTuple,
    VennProtocolFeeSetEvent.OutputTuple,
    VennProtocolFeeSetEvent.OutputObject
  >;

  filters: {
    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AttestationCenterSet(address)": TypedContractEvent<
      AttestationCenterSetEvent.InputTuple,
      AttestationCenterSetEvent.OutputTuple,
      AttestationCenterSetEvent.OutputObject
    >;
    AttestationCenterSet: TypedContractEvent<
      AttestationCenterSetEvent.InputTuple,
      AttestationCenterSetEvent.OutputTuple,
      AttestationCenterSetEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ProtocolDetectionApproved(address,address,address[],address[],string)": TypedContractEvent<
      ProtocolDetectionApprovedEvent.InputTuple,
      ProtocolDetectionApprovedEvent.OutputTuple,
      ProtocolDetectionApprovedEvent.OutputObject
    >;
    ProtocolDetectionApproved: TypedContractEvent<
      ProtocolDetectionApprovedEvent.InputTuple,
      ProtocolDetectionApprovedEvent.OutputTuple,
      ProtocolDetectionApprovedEvent.OutputObject
    >;

    "ProtocolDetectionRegistered(address,address,address[],address[],uint256,string)": TypedContractEvent<
      ProtocolDetectionRegisteredEvent.InputTuple,
      ProtocolDetectionRegisteredEvent.OutputTuple,
      ProtocolDetectionRegisteredEvent.OutputObject
    >;
    ProtocolDetectionRegistered: TypedContractEvent<
      ProtocolDetectionRegisteredEvent.InputTuple,
      ProtocolDetectionRegisteredEvent.OutputTuple,
      ProtocolDetectionRegisteredEvent.OutputObject
    >;

    "ProtocolRegistered(address,string)": TypedContractEvent<
      ProtocolRegisteredEvent.InputTuple,
      ProtocolRegisteredEvent.OutputTuple,
      ProtocolRegisteredEvent.OutputObject
    >;
    ProtocolRegistered: TypedContractEvent<
      ProtocolRegisteredEvent.InputTuple,
      ProtocolRegisteredEvent.OutputTuple,
      ProtocolRegisteredEvent.OutputObject
    >;

    "ProtocolUpdated(address,string)": TypedContractEvent<
      ProtocolUpdatedEvent.InputTuple,
      ProtocolUpdatedEvent.OutputTuple,
      ProtocolUpdatedEvent.OutputObject
    >;
    ProtocolUpdated: TypedContractEvent<
      ProtocolUpdatedEvent.InputTuple,
      ProtocolUpdatedEvent.OutputTuple,
      ProtocolUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubnetSubscribed(address,uint16,uint256[])": TypedContractEvent<
      SubnetSubscribedEvent.InputTuple,
      SubnetSubscribedEvent.OutputTuple,
      SubnetSubscribedEvent.OutputObject
    >;
    SubnetSubscribed: TypedContractEvent<
      SubnetSubscribedEvent.InputTuple,
      SubnetSubscribedEvent.OutputTuple,
      SubnetSubscribedEvent.OutputObject
    >;

    "SubnetUnsubscribed(address,uint16)": TypedContractEvent<
      SubnetUnsubscribedEvent.InputTuple,
      SubnetUnsubscribedEvent.OutputTuple,
      SubnetUnsubscribedEvent.OutputObject
    >;
    SubnetUnsubscribed: TypedContractEvent<
      SubnetUnsubscribedEvent.InputTuple,
      SubnetUnsubscribedEvent.OutputTuple,
      SubnetUnsubscribedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VennDetectionFeeSet(uint256)": TypedContractEvent<
      VennDetectionFeeSetEvent.InputTuple,
      VennDetectionFeeSetEvent.OutputTuple,
      VennDetectionFeeSetEvent.OutputObject
    >;
    VennDetectionFeeSet: TypedContractEvent<
      VennDetectionFeeSetEvent.InputTuple,
      VennDetectionFeeSetEvent.OutputTuple,
      VennDetectionFeeSetEvent.OutputObject
    >;

    "VennFeeRecipientSet(address)": TypedContractEvent<
      VennFeeRecipientSetEvent.InputTuple,
      VennFeeRecipientSetEvent.OutputTuple,
      VennFeeRecipientSetEvent.OutputObject
    >;
    VennFeeRecipientSet: TypedContractEvent<
      VennFeeRecipientSetEvent.InputTuple,
      VennFeeRecipientSetEvent.OutputTuple,
      VennFeeRecipientSetEvent.OutputObject
    >;

    "VennProtocolFeeSet(uint256)": TypedContractEvent<
      VennProtocolFeeSetEvent.InputTuple,
      VennProtocolFeeSetEvent.OutputTuple,
      VennProtocolFeeSetEvent.OutputObject
    >;
    VennProtocolFeeSet: TypedContractEvent<
      VennProtocolFeeSetEvent.InputTuple,
      VennProtocolFeeSetEvent.OutputTuple,
      VennProtocolFeeSetEvent.OutputObject
    >;
  };
}
