/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface VennFirewallConsumerBaseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptFirewallAdmin"
      | "firewallAdmin"
      | "safeFunctionCall"
      | "setAllowNonZeroUserNativeFee"
      | "setAttestationCenterProxy"
      | "setFirewall"
      | "setFirewallAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AttestationCenterProxyUpdated"
      | "FirewallAdminProposed"
      | "FirewallAdminUpdated"
      | "FirewallUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptFirewallAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "firewallAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeFunctionCall",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowNonZeroUserNativeFee",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestationCenterProxy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFirewall",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFirewallAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptFirewallAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "firewallAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeFunctionCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowNonZeroUserNativeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttestationCenterProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFirewall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFirewallAdmin",
    data: BytesLike
  ): Result;
}

export namespace AttestationCenterProxyUpdatedEvent {
  export type InputTuple = [newAttestationCenterProxy: AddressLike];
  export type OutputTuple = [newAttestationCenterProxy: string];
  export interface OutputObject {
    newAttestationCenterProxy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirewallAdminProposedEvent {
  export type InputTuple = [newAdmin: AddressLike];
  export type OutputTuple = [newAdmin: string];
  export interface OutputObject {
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirewallAdminUpdatedEvent {
  export type InputTuple = [newAdmin: AddressLike];
  export type OutputTuple = [newAdmin: string];
  export interface OutputObject {
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FirewallUpdatedEvent {
  export type InputTuple = [newFirewall: AddressLike];
  export type OutputTuple = [newFirewall: string];
  export interface OutputObject {
    newFirewall: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VennFirewallConsumerBase extends BaseContract {
  connect(runner?: ContractRunner | null): VennFirewallConsumerBase;
  waitForDeployment(): Promise<this>;

  interface: VennFirewallConsumerBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptFirewallAdmin: TypedContractMethod<[], [void], "nonpayable">;

  firewallAdmin: TypedContractMethod<[], [string], "view">;

  safeFunctionCall: TypedContractMethod<
    [_userNativeFee: BigNumberish, _proxyPayload: BytesLike, _data: BytesLike],
    [void],
    "payable"
  >;

  setAllowNonZeroUserNativeFee: TypedContractMethod<
    [_allowNonZeroUserNativeFee: boolean],
    [void],
    "nonpayable"
  >;

  setAttestationCenterProxy: TypedContractMethod<
    [_attestationCenterProxy: AddressLike],
    [void],
    "nonpayable"
  >;

  setFirewall: TypedContractMethod<
    [_firewall: AddressLike],
    [void],
    "nonpayable"
  >;

  setFirewallAdmin: TypedContractMethod<
    [_firewallAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptFirewallAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "firewallAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "safeFunctionCall"
  ): TypedContractMethod<
    [_userNativeFee: BigNumberish, _proxyPayload: BytesLike, _data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setAllowNonZeroUserNativeFee"
  ): TypedContractMethod<
    [_allowNonZeroUserNativeFee: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttestationCenterProxy"
  ): TypedContractMethod<
    [_attestationCenterProxy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFirewall"
  ): TypedContractMethod<[_firewall: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFirewallAdmin"
  ): TypedContractMethod<[_firewallAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AttestationCenterProxyUpdated"
  ): TypedContractEvent<
    AttestationCenterProxyUpdatedEvent.InputTuple,
    AttestationCenterProxyUpdatedEvent.OutputTuple,
    AttestationCenterProxyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FirewallAdminProposed"
  ): TypedContractEvent<
    FirewallAdminProposedEvent.InputTuple,
    FirewallAdminProposedEvent.OutputTuple,
    FirewallAdminProposedEvent.OutputObject
  >;
  getEvent(
    key: "FirewallAdminUpdated"
  ): TypedContractEvent<
    FirewallAdminUpdatedEvent.InputTuple,
    FirewallAdminUpdatedEvent.OutputTuple,
    FirewallAdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FirewallUpdated"
  ): TypedContractEvent<
    FirewallUpdatedEvent.InputTuple,
    FirewallUpdatedEvent.OutputTuple,
    FirewallUpdatedEvent.OutputObject
  >;

  filters: {
    "AttestationCenterProxyUpdated(address)": TypedContractEvent<
      AttestationCenterProxyUpdatedEvent.InputTuple,
      AttestationCenterProxyUpdatedEvent.OutputTuple,
      AttestationCenterProxyUpdatedEvent.OutputObject
    >;
    AttestationCenterProxyUpdated: TypedContractEvent<
      AttestationCenterProxyUpdatedEvent.InputTuple,
      AttestationCenterProxyUpdatedEvent.OutputTuple,
      AttestationCenterProxyUpdatedEvent.OutputObject
    >;

    "FirewallAdminProposed(address)": TypedContractEvent<
      FirewallAdminProposedEvent.InputTuple,
      FirewallAdminProposedEvent.OutputTuple,
      FirewallAdminProposedEvent.OutputObject
    >;
    FirewallAdminProposed: TypedContractEvent<
      FirewallAdminProposedEvent.InputTuple,
      FirewallAdminProposedEvent.OutputTuple,
      FirewallAdminProposedEvent.OutputObject
    >;

    "FirewallAdminUpdated(address)": TypedContractEvent<
      FirewallAdminUpdatedEvent.InputTuple,
      FirewallAdminUpdatedEvent.OutputTuple,
      FirewallAdminUpdatedEvent.OutputObject
    >;
    FirewallAdminUpdated: TypedContractEvent<
      FirewallAdminUpdatedEvent.InputTuple,
      FirewallAdminUpdatedEvent.OutputTuple,
      FirewallAdminUpdatedEvent.OutputObject
    >;

    "FirewallUpdated(address)": TypedContractEvent<
      FirewallUpdatedEvent.InputTuple,
      FirewallUpdatedEvent.OutputTuple,
      FirewallUpdatedEvent.OutputObject
    >;
    FirewallUpdated: TypedContractEvent<
      FirewallUpdatedEvent.InputTuple,
      FirewallUpdatedEvent.OutputTuple,
      FirewallUpdatedEvent.OutputObject
    >;
  };
}
