/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  VennFirewallConsumerBase,
  VennFirewallConsumerBaseInterface,
} from "../VennFirewallConsumerBase";

const _abi = [
  {
    inputs: [],
    name: "AttestationCenterProxyNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "NonZeroUserNativeFee",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughFee",
    type: "error",
  },
  {
    inputs: [],
    name: "NotFirewallAdmin",
    type: "error",
  },
  {
    inputs: [],
    name: "NotNewFirewallAdmin",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "returnData",
        type: "bytes",
      },
    ],
    name: "ProxyCallFailed",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newAttestationCenterProxy",
        type: "address",
      },
    ],
    name: "AttestationCenterProxyUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "FirewallAdminProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newAdmin",
        type: "address",
      },
    ],
    name: "FirewallAdminUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newFirewall",
        type: "address",
      },
    ],
    name: "FirewallUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptFirewallAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "firewallAdmin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_userNativeFee",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_proxyPayload",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "safeFunctionCall",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_allowNonZeroUserNativeFee",
        type: "bool",
      },
    ],
    name: "setAllowNonZeroUserNativeFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_attestationCenterProxy",
        type: "address",
      },
    ],
    name: "setAttestationCenterProxy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_firewall",
        type: "address",
      },
    ],
    name: "setFirewall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_firewallAdmin",
        type: "address",
      },
    ],
    name: "setFirewallAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VennFirewallConsumerBase__factory {
  static readonly abi = _abi;
  static createInterface(): VennFirewallConsumerBaseInterface {
    return new Interface(_abi) as VennFirewallConsumerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VennFirewallConsumerBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as VennFirewallConsumerBase;
  }
}
